<a href="https://colab.research.google.com/github/Ishikaaa/Machine-Learning-Assignments/blob/master/(Ass_15)Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1. Import MNIST dataset from sklearn -***

In [0]:
import pandas as pd 
import numpy as np 
import seaborn as sns 

In [0]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_digits

In [63]:
digi=load_digits()
print(digi)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [64]:
X=digi.data 
Y=digi.target 
print(X)
print(Y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


# ***2. Perform feature scaling -***

In [65]:
from sklearn.preprocessing import StandardScaler 
X=StandardScaler().fit_transform(X)
print(X)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


In [11]:
print("Shape of X:",X.shape)

Shape of X: (1797, 64)


# ***3. Split data into training and testing sets -***

In [0]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

# ***4. Perform PCA -***

In [0]:
from sklearn.decomposition import PCA 

In [0]:
ppca=PCA(n_components=2)
X_train=ppca.fit_transform(X_train)
X_test=ppca.fit_transform(X_test)

In [69]:
print("Shape of X_train:",X_train.shape)
print("Shape of X_test:",X_test.shape)

Shape of X_train: (1257, 2)
Shape of X_test: (540, 2)


# ***5. Perform classification (logistic regression) - ***

In [70]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
# Making Predictions 
Y_pred=log.predict(X_test)

# ***6. Print the following :***

In [0]:
from sklearn import metrics

**a. Accuracy Score - **

In [72]:
metrics.accuracy_score(Y_test,Y_pred)

0.2111111111111111

**b. Confusion Matrix -**

In [74]:
print(metrics.confusion_matrix(Y_test,Y_pred))

[[ 0 32  0  0  1  1  0 11  0  0]
 [ 8 22  0  3 10  0  0  7  0  2]
 [ 0  1 32 13  2  2  1  0  0  2]
 [ 1  0 25  9  0  2 15  0  0  2]
 [ 0  6  0  0 37  0  0  5  0  0]
 [19  5  4  6  1  2  9  0  0 11]
 [ 0  0  0  0  0  0  0 60  0  0]
 [15  4  1  0 11  0 20  0  0  2]
 [ 8 13  9  3  1  6  3  1  0 17]
 [ 7  2 18  8  4  3  3  0  0 12]]


**c. Classification Report -**

In [75]:
print(metrics.classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        45
           1       0.26      0.42      0.32        52
           2       0.36      0.60      0.45        53
           3       0.21      0.17      0.19        54
           4       0.55      0.77      0.64        48
           5       0.12      0.04      0.05        57
           6       0.00      0.00      0.00        60
           7       0.00      0.00      0.00        53
           8       0.00      0.00      0.00        61
           9       0.25      0.21      0.23        57

   micro avg       0.21      0.21      0.21       540
   macro avg       0.18      0.22      0.19       540
weighted avg       0.17      0.21      0.18       540



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
