<a href="https://colab.research.google.com/github/Ishikaaa/Machine-Learning-Assignments/blob/master/(Ass_13)Support_Vector_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1. Load the dataset from sklearn -***

In [0]:
import pandas as pd 
import numpy as np 

In [0]:
from sklearn import datasets 
data=datasets.load_digits()
X=data.data 
Y=data.target 

In [3]:
type(X)

numpy.ndarray

In [4]:
print("Shape of X",X.shape)
print("Shape of Y:",Y.shape)

Shape of X (1797, 64)
Shape of Y: (1797,)


In [5]:
Y=Y.reshape((1797,1))
print("Shape of Y:",Y.shape)

Shape of Y: (1797, 1)


# ***2. Split the dataset into training and testing sets - ***

In [6]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)
X_train,X_test,Y_train,Y_test

(array([[ 0.,  3., 13., ..., 12.,  9.,  1.],
        [ 0.,  0.,  1., ..., 13.,  1.,  0.],
        [ 0.,  0.,  4., ...,  9.,  0.,  0.],
        ...,
        [ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  4., ...,  0.,  0.,  0.],
        [ 0.,  0.,  6., ..., 11.,  0.,  0.]]),
 array([[ 0.,  0., 11., ..., 13., 16.,  8.],
        [ 0.,  1., 15., ...,  1.,  0.,  0.],
        [ 0.,  2., 13., ..., 16., 16.,  3.],
        ...,
        [ 0.,  0., 11., ...,  7.,  0.,  0.],
        [ 0.,  0.,  5., ...,  7.,  0.,  0.],
        [ 0.,  2., 14., ...,  6.,  0.,  0.]]),
 array([[2],
        [8],
        [9],
        ...,
        [7],
        [7],
        [8]]),
 array([[2],
        [8],
        [2],
        [6],
        [6],
        [7],
        [1],
        [9],
        [8],
        [5],
        [2],
        [8],
        [6],
        [6],
        [6],
        [6],
        [1],
        [0],
        [5],
        [8],
        [8],
        [7],
        [8],
        [4],
        [7],
        [5],

# ***3. Use SVM with kernels -***

In [0]:
from sklearn.svm import SVC 
from sklearn import metrics 

**a. Linear -**

In [12]:
classifierL=SVC(kernel='linear',degree=8)
classifierL.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
# Making Predictions - 
Y_predL=classifierL.predict(X_test)

In [18]:
# confusion Matrix --
con=metrics.confusion_matrix(Y_test,Y_predL)
con

array([[37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 42,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0, 44,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 43,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 47,  0,  0,  0,  1],
       [ 0,  1,  0,  0,  0,  0, 51,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 47,  0,  0],
       [ 0,  3,  1,  0,  0,  0,  0,  0, 44,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  1, 44]])

In [19]:
# classification report -- 
print(metrics.classification_report(Y_test,Y_predL))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.91      0.98      0.94        43
           2       0.98      1.00      0.99        44
           3       0.98      0.96      0.97        45
           4       0.97      1.00      0.99        38
           5       0.98      0.98      0.98        48
           6       1.00      0.98      0.99        52
           7       1.00      0.98      0.99        48
           8       0.94      0.92      0.93        48
           9       0.96      0.94      0.95        47

   micro avg       0.97      0.97      0.97       450
   macro avg       0.97      0.97      0.97       450
weighted avg       0.97      0.97      0.97       450



**Note - **

1.   97% accuracy while using Linear Kernel.



**b. Poly -**

In [21]:
classifierP=SVC(kernel='poly')
classifierP.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
# Making Predictions -- 
Y_predP=classifierP.predict(X_test)

In [25]:
# Confusion Matrix -- 
conP=metrics.confusion_matrix(Y_test,Y_predP)
conP

array([[37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 42,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0, 44,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 47,  0,  0,  0,  1],
       [ 0,  1,  0,  0,  0,  0, 51,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 48,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0, 45,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0, 46]])

In [26]:
# classification report -- 
print(metrics.classification_report(Y_test,Y_predP))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.91      0.98      0.94        43
           2       1.00      1.00      1.00        44
           3       1.00      0.98      0.99        45
           4       1.00      1.00      1.00        38
           5       0.98      0.98      0.98        48
           6       1.00      0.98      0.99        52
           7       1.00      1.00      1.00        48
           8       0.96      0.94      0.95        48
           9       0.98      0.98      0.98        47

   micro avg       0.98      0.98      0.98       450
   macro avg       0.98      0.98      0.98       450
weighted avg       0.98      0.98      0.98       450



**Note - **

1.   98% accuracy while using Polynomial kernel. 



**c. Gaussian OR RBF kernel - **

In [27]:
classifierR=SVC(kernel='rbf')
classifierR.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
# Making Predictions --
Y_predR=classifierR.predict(X_test)

In [32]:
# Confusion Matrix -- 
conR=metrics.confusion_matrix(Y_test,Y_predR)
conR

array([[24,  0,  0,  0, 13,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0, 33,  0,  0,  0,  0,  0],
       [ 0,  0, 17,  0, 27,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 42,  3,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 32, 16,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 24,  0, 28,  0,  0,  0],
       [ 0,  0,  0,  0, 31,  0,  0, 17,  0,  0],
       [ 0,  0,  0,  0, 47,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 21,  0,  0,  0,  0, 26]])

In [34]:
# Classification Report -- 
print(metrics.classification_report(Y_test,Y_predR))

              precision    recall  f1-score   support

           0       1.00      0.65      0.79        37
           1       1.00      0.23      0.38        43
           2       1.00      0.39      0.56        44
           3       1.00      0.93      0.97        45
           4       0.14      1.00      0.25        38
           5       1.00      0.33      0.50        48
           6       1.00      0.54      0.70        52
           7       1.00      0.35      0.52        48
           8       1.00      0.02      0.04        48
           9       1.00      0.55      0.71        47

   micro avg       0.49      0.49      0.49       450
   macro avg       0.91      0.50      0.54       450
weighted avg       0.93      0.49      0.54       450



**Note - **



1.   93% accuracy while using Guassian kernel. 





**d. Sigmoid - **

In [35]:
classifierS=SVC(kernel='sigmoid')
classifierS.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
# Making Predictions --
Y_predS=classifierS.predict(X_test)

In [39]:
# confussion matrix 
conS=metrics.confusion_matrix(Y_test,Y_predS)
conS

array([[ 0,  0,  0,  0, 37,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 43,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 44,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 45,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 52,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 47,  0,  0,  0,  0,  0]])

In [40]:
# classification report -- 
print(metrics.classification_report(Y_test,Y_predS))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        37
           1       0.00      0.00      0.00        43
           2       0.00      0.00      0.00        44
           3       0.00      0.00      0.00        45
           4       0.08      1.00      0.16        38
           5       0.00      0.00      0.00        48
           6       0.00      0.00      0.00        52
           7       0.00      0.00      0.00        48
           8       0.00      0.00      0.00        48
           9       0.00      0.00      0.00        47

   micro avg       0.08      0.08      0.08       450
   macro avg       0.01      0.10      0.02       450
weighted avg       0.01      0.08      0.01       450



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


** Note - **


1.   1% accuracy while using Sigmoid kernel. 

