<a href="https://colab.research.google.com/github/Ishikaaa/Machine-Learning-Assignments/blob/master/(Ass_16)Ensemble_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1. Load the dataset from sklearn. Store the data and target values in variables -***

In [0]:
import numpy as np 
import pandas as pd 

In [0]:
from sklearn.datasets import load_digits
data=load_digits()
data

{'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttp://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of

In [0]:
X=data.data 
Y=data.target 
print(X)
print(Y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


In [0]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
X_train,X_test,Y_train,Y_test

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  7., ..., 16.,  4.,  0.],
        [ 0.,  0.,  0., ..., 12.,  8.,  0.],
        ...,
        [ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  4., ...,  0.,  0.,  0.],
        [ 0.,  0.,  6., ..., 11.,  0.,  0.]]),
 array([[ 0.,  0., 11., ..., 13., 16.,  8.],
        [ 0.,  1., 15., ...,  1.,  0.,  0.],
        [ 0.,  2., 13., ..., 16., 16.,  3.],
        ...,
        [ 0.,  0.,  0., ..., 15.,  1.,  0.],
        [ 0.,  0.,  8., ...,  2.,  0.,  0.],
        [ 0.,  0.,  1., ..., 11.,  1.,  0.]]),
 array([9, 3, 6, ..., 7, 7, 8]),
 array([2, 8, 2, 6, 6, 7, 1, 9, 8, 5, 2, 8, 6, 6, 6, 6, 1, 0, 5, 8, 8, 7,
        8, 4, 7, 5, 4, 9, 2, 9, 4, 7, 6, 8, 9, 4, 3, 1, 0, 1, 8, 6, 7, 7,
        1, 0, 7, 6, 2, 1, 9, 6, 7, 9, 0, 0, 5, 1, 6, 3, 0, 2, 3, 4, 1, 9,
        2, 6, 9, 1, 8, 3, 5, 1, 2, 8, 2, 2, 9, 7, 2, 3, 6, 0, 5, 3, 7, 5,
        1, 2, 9, 9, 3, 1, 7, 7, 4, 8, 5, 8, 5, 5, 2, 5, 9, 0, 7, 1, 4, 7,
        3, 4, 8, 9, 7, 9, 8

# ***2. Perform the following ensemble methods -***

In [0]:
from sklearn import metrics 

**a. Bagged Decision Trees - **

In [0]:
from sklearn.tree import DecisionTreeClassifier
calss=DecisionTreeClassifier(criterion='gini')
calss.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
# Making The Prediction 
Y_pred=calss.predict(X_test)

In [0]:
# Accuracy Score 
print("Accuracy:",metrics.accuracy_score(Y_test,Y_pred))

Accuracy: 0.8314814814814815


In [0]:
print("Confusion Matrix:")
metrics.confusion_matrix(Y_test,Y_pred)

Confusion Matrix:


array([[41,  0,  0,  0,  0,  1,  1,  0,  0,  2],
       [ 0, 40,  0,  0,  2,  1,  2,  1,  6,  0],
       [ 1,  0, 40,  5,  1,  0,  0,  1,  2,  3],
       [ 0,  0,  4, 48,  0,  0,  0,  1,  1,  0],
       [ 1,  0,  0,  0, 43,  1,  1,  1,  1,  0],
       [ 1,  0,  0,  4,  0, 47,  1,  1,  1,  2],
       [ 1,  1,  1,  0,  3,  0, 54,  0,  0,  0],
       [ 0,  2,  0,  3,  1,  0,  0, 45,  1,  1],
       [ 1,  5,  2,  4,  0,  0,  0,  0, 44,  5],
       [ 0,  0,  0,  3,  0,  3,  0,  1,  3, 47]])

**b. Random Forest Classification - **

In [0]:
from sklearn.ensemble import RandomForestClassifier 
rfc=RandomForestClassifier(n_estimators=10)
rfc.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [0]:
# Making Predictions 
Y_pred=rfc.predict(X_test)

In [0]:
# Accuracy Score 
print("Accuracy:",metrics.accuracy_score(Y_test,Y_pred))

Accuracy: 0.95


In [0]:
# confusion matrix 
print("Confusion Matrix:")
metrics.confusion_matrix(Y_test,Y_pred)

Confusion Matrix:


array([[45,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 50,  0,  0,  0,  1,  0,  1,  0,  0],
       [ 1,  0, 49,  2,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  3, 51,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 47,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 54,  1,  0,  0,  2],
       [ 0,  1,  0,  0,  0,  1, 58,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 53,  0,  0],
       [ 0,  2,  1,  0,  0,  4,  0,  1, 51,  2],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  0, 55]])

**c. Stochastic Gradient Boosting Classification -**

In [0]:
from sklearn.ensemble import GradientBoostingClassifier
seed=7
num_tress=100 # number of trees = 100 
gra=GradientBoostingClassifier(n_estimators=num_tress,random_state=seed)
gra.fit(X_train,Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=7,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [0]:
# making the predictions 
Y_predG=gra.predict(X_test)

In [0]:
# Accuracy Score 
print("Accuracy:",metrics.accuracy_score(Y_test,Y_predG))

Accuracy: 0.9518518518518518


In [0]:
# Confusion Matrix 
print("Confusion Matrix:")
metrics.confusion_matrix(Y_test,Y_predG)

Confusion Matrix:


array([[44,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0, 50,  0,  0,  1,  0,  0,  0,  0,  1],
       [ 1,  1, 50,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, 50,  0,  0,  0,  0,  2,  2],
       [ 0,  0,  0,  0, 46,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 55,  0,  0,  0,  2],
       [ 0,  0,  1,  0,  0,  0, 57,  0,  2,  0],
       [ 0,  0,  0,  0,  2,  0,  0, 50,  0,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 59,  1],
       [ 1,  0,  0,  1,  0,  1,  0,  0,  1, 53]])

**d. Voting Ensemble (Decision Tree, Logistic Regression, SVM) - **

In [0]:
from sklearn.tree import DecisionTreeClassifier
from sklearn .linear_model import LogisticRegression
from sklearn.svm import SVC 

cl1=DecisionTreeClassifier()
cl2=LogisticRegression()
cl3=SVC()

In [0]:
from sklearn.ensemble import VotingClassifier
ensem=VotingClassifier(estimators=[('dc',cl1),('lr',cl2),('scv',cl3)])
ensem.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


VotingClassifier(estimators=[('dc', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf...f', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=None, voting='hard', weights=None)

In [0]:
# Making the predictions 
Y_predE=ensem.predict(X_test)

In [0]:
# Accuracy Score 
print("Accuracy:",metrics.accuracy_score(Y_test,Y_predE))

Accuracy: 0.8888888888888888


In [0]:
# confusion matrix 
print("Confusion Matrix:")
metrics.confusion_matrix(Y_test,Y_predE)

Confusion Matrix:


array([[44,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 49,  0,  1,  1,  0,  1,  0,  0,  0],
       [ 1,  2, 47,  2,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  2, 52,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  1,  4, 50,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  4,  0, 55,  0,  0,  0],
       [ 0,  2,  0,  1,  3,  0,  0, 47,  0,  0],
       [ 1,  8,  1,  4,  5,  0,  0,  0, 42,  0],
       [ 0,  0,  0,  4,  7,  0,  0,  0,  0, 46]])