<a href="https://colab.research.google.com/github/Ishikaaa/Machine-Learning-Assignments/blob/master/(Ass_14)Decision_Trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1. Import the libraries and dataset -***

In [0]:
import pandas as pd 
import numpy as np 

In [2]:
dataset=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data")
dataset.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [4]:
print("Shape of dataset:",dataset.shape)

Shape of dataset: (624, 5)


In [5]:
print("Name of all columns:",dataset.columns)

Name of all columns: Index(['B', '1', '1.1', '1.2', '1.3'], dtype='object')


In [6]:
dataset.isnull().sum()

B      0
1      0
1.1    0
1.2    0
1.3    0
dtype: int64

# ***2. Slice the dataset -***

In [7]:
dataset.isnull().sum()

B      0
1      0
1.1    0
1.2    0
1.3    0
dtype: int64

In [0]:
X=dataset.iloc[:,1:].values
Y=dataset.iloc[:,0:1].values

In [9]:
print(X)

[[1 1 1 2]
 [1 1 1 3]
 [1 1 1 4]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]]


In [10]:
print(Y)

[['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['L']
 ['B']
 ['R']
 ['R']
 ['R']
 ['B']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['L']
 ['L']
 ['B']
 ['R']
 ['R']
 ['L']
 ['R']
 ['R']
 ['R']
 ['R']
 ['B']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['L']
 ['L']
 ['L']
 ['B']
 ['R']
 ['L']
 ['B']
 ['R']
 ['R']
 ['R']
 ['L']
 ['R']
 ['R']
 ['R']
 ['R']
 ['B']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['L']
 ['L']
 ['L']
 ['L']
 ['B']
 ['L']
 ['L']
 ['R']
 ['R']
 ['R']
 ['L']
 ['R']
 ['R']
 ['R']
 ['R']
 ['L']
 ['R']
 ['R']
 ['R']
 ['R']
 ['B']
 ['R']
 ['R']
 ['R']
 ['R']
 ['L']
 ['B']
 ['R']
 ['R']
 ['R']
 ['B']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']
 ['R']

# ***3. Split the dataset by using train_test_split() - ***

In [0]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

# ***4. Use DecisionTree - ***

In [0]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

**a. Gini - **

In [13]:
gi=DecisionTreeClassifier(criterion='gini')
gi.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
# Making Predictions - 
Y_predG=gi.predict(X_test)

In [15]:
# Accuracy Score - 
metrics.accuracy_score(Y_test,Y_predG)

0.7628205128205128

In [20]:
# classification report 
print(metrics.classification_report(Y_test,Y_predG))

              precision    recall  f1-score   support

           B       0.04      0.11      0.06         9
           L       0.85      0.76      0.80        72
           R       0.93      0.84      0.88        75

   micro avg       0.76      0.76      0.76       156
   macro avg       0.61      0.57      0.58       156
weighted avg       0.84      0.76      0.80       156



**Note - **


1.   84% accuracy while using gini decision treee algorithm. 



**b. Entropy - 
**

In [17]:
ent=DecisionTreeClassifier(criterion='entropy')
ent.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
# Making the prediction 
Y_predE=ent.predict(X_test)

In [19]:
# Accuracy 
metrics.accuracy_score(Y_test,Y_predE)

0.75

In [22]:
# classification report 
print(metrics.classification_report(Y_test,Y_predE))

              precision    recall  f1-score   support

           B       0.04      0.11      0.06         9
           L       0.84      0.75      0.79        72
           R       0.94      0.83      0.88        75

   micro avg       0.75      0.75      0.75       156
   macro avg       0.61      0.56      0.58       156
weighted avg       0.84      0.75      0.79       156



**Note - **


1.   84% accuracy while using entropy decision tree algo.

