<a href="https://colab.research.google.com/github/Ishikaaa/Machine-Learning-Assignments/blob/master/(Ass_12)Naive_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***1. What is the probability of a person playing when the weather is sunny? Find P(Yes|Sunny) - ***





In [0]:
# Weather	   Play
# Sunny	     No
# Overcast	 Yes
# Rainy	     Yes
# Sunny	     Yes
# Sunny	     Yes
# Overcast	 Yes
# Rainy	     No
# Rainy	     No
# Sunny	     Yes
# Rainy	     Yes
# Sunny	     No
# Overcast	 Yes
# Overcast	 Yes
# Rainy	     No

P(Yes/Sunny)=3/5

# ***2. Solve following:***

***a. Import iris dataset from sklearn - ***

In [0]:
import pandas as pd 
import numpy as np 

In [0]:
from sklearn import datasets 
iris=datasets.load_iris()
x=iris.data
y=iris.target

# ***2. Split the dataset into training and testing sets -***

In [5]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.25,random_state=0)
X_train,X_test,Y_train,Y_test

(array([[5.9, 3. , 4.2, 1.5],
        [5.8, 2.6, 4. , 1.2],
        [6.8, 3. , 5.5, 2.1],
        [4.7, 3.2, 1.3, 0.2],
        [6.9, 3.1, 5.1, 2.3],
        [5. , 3.5, 1.6, 0.6],
        [5.4, 3.7, 1.5, 0.2],
        [5. , 2. , 3.5, 1. ],
        [6.5, 3. , 5.5, 1.8],
        [6.7, 3.3, 5.7, 2.5],
        [6. , 2.2, 5. , 1.5],
        [6.7, 2.5, 5.8, 1.8],
        [5.6, 2.5, 3.9, 1.1],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.3, 4.7, 1.6],
        [5.5, 2.4, 3.8, 1.1],
        [6.3, 2.7, 4.9, 1.8],
        [6.3, 2.8, 5.1, 1.5],
        [4.9, 2.5, 4.5, 1.7],
        [6.3, 2.5, 5. , 1.9],
        [7. , 3.2, 4.7, 1.4],
        [6.5, 3. , 5.2, 2. ],
        [6. , 3.4, 4.5, 1.6],
        [4.8, 3.1, 1.6, 0.2],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.7, 4.2, 1.3],
        [5.6, 2.9, 3.6, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [6.1, 3. , 4.6, 1.4],
        [7.2, 3.2, 6. , 1.8],
        [5.3, 3.7, 1.5, 0.2],
        [4.3, 3. , 1.1, 0.1],
        [6.4, 2.7, 5.3, 1.9],
        [5

**a. Use GaussianNB -**

In [6]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
# predicting values 
Y_pre=nb.predict(X_test)
print("Predicted Values:",Y_pre,"\n","Actual Values  :",Y_test)

Predicted Values: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1] 
 Actual Values  : [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


**i. Confusion matrix - **

In [14]:
from sklearn.metrics import confusion_matrix
con=confusion_matrix(Y_test,Y_pre)
con

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

**ii. Classification report -**

In [16]:
from sklearn import metrics 
print(metrics.classification_report(Y_test,Y_pre))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

   micro avg       1.00      1.00      1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



**d) Use MultinomialNB -**

In [17]:
from sklearn.naive_bayes import MultinomialNB 
mn=MultinomialNB()
mn.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

**i. Confusion matrix -**

In [0]:
Y_pre=mn.predict(X_test)

In [20]:
print("Predicted Values:",Y_pre)
print("Actual Values   :",Y_test)

Predicted Values: [2 2 0 2 0 2 0 2 2 2 2 2 2 2 2 0 2 2 0 0 2 2 0 0 2 0 0 2 2 0 2 2 0 2 2 2 0
 2]
Actual Values   : [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


In [21]:
from sklearn.metrics import confusion_matrix 
con=confusion_matrix(Y_test,Y_pre)
con

array([[13,  0,  0],
       [ 0,  0, 16],
       [ 0,  0,  9]])

**ii. Classification report -**

In [22]:
from sklearn import metrics 
print(metrics.classification_report(Y_test,Y_pre))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.00      0.00      0.00        16
           2       0.36      1.00      0.53         9

   micro avg       0.58      0.58      0.58        38
   macro avg       0.45      0.67      0.51        38
weighted avg       0.43      0.58      0.47        38



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
